version: "3.9"

services:
  dnd-chronicle-bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # При необходимости можно переопределить путь к Vault внутри контейнера
      VAULT_PATH: /vault
    volumes:
      # Сабмодуль с Obsidian Vault (Chronicle-vault) монтируется внутрь контейнера
      - ./Chronicle-vault:/vault
    # Если нужно пользоваться SSH-ключами/конфигом git хоста, можно пробросить ~/.ssh
    # volumes:
    #   - ./vault:/vault
      - ~/.ssh:/root/.ssh:ro

